### PR TITLE
Display same information whether student, staff, or faculty is searching

### PR DESCRIPTION
**Pull request by C0urante**

### CODE REVIEW

**Comment by aborroni** [comment]
Chris,

The staff are seeing what they need to see but now the faculty can't see
the extended listings i.e. columns 2 and 3.

Albert Borroni, Ph.D. '85
Director, OCTET / Lecturer Computer Science
Oberlin College
Oberlin, Ohio 44074

440 775-8345
http://www.oberlin.edu/OCTE http://www.oberlin.edu/OCTETT
http://www.oberlin.edu/OCTET

http://www.oberlin.edu/OCTET

**Comment by C0urante** [comment]
Oh, I think I may have misunderstood the changes you wanted. Did we want to completely eliminate privileged information from being displayed, or did we only want to change the view of the staff (and not faculty) to be identical to that of students?

**Comment by aborroni** [comment]
The latter.

Faculty should still be able to see the privileged information.

Albert Borroni, Ph.D.
Director, OCTET / Lecturer Computer Science
Oberlin College
Oberlin, Ohio 44074

440 775-8345
http://www.oberlin.edu/OCTET

**Comment by C0urante** [comment]
Noted. Closing this PR, will create a new one with the correct changes.

**Pull request closed without merging**
